### ISSUE TITLE
Move build / rebuild to Github Actions

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/subject-set-search-api#11]
Due to future deprecation of Jenkins, build and rebuild actions should be moved to Github Actions.

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/front-end-monorepo/pull/2531 has a deploy workflow that should be easy to adapt here.

**Comment by eatyourgreens** [comment]
Deploy via GH Actions is working now. Do we want to turn off Jenkins (and the associated Lita command?)

**Comment by lcjohnso** [comment]
@eatyourgreens (cc @camallen) -- Great!  Wonderful to have this deploy off of Jenkins.  For the Lita command, however: this is what Sam needs to use to rebuild the index (when project teams update subject sets + workflows) and I don't believe she has the repo access to trigger the GH Action.

Is it possible to edit the Lita command to trigger the GH Action?  That is a high priority to get enabled, so non-devs have access to trigger that action.  I opened a new issue on the [Lita repo](https://github.com/zooniverse/lita): https://github.com/zooniverse/lita/issues/138

**Comment by eatyourgreens** [comment]
I think there would be a substantial security risk there: allowing Lita to run private GH API calls.
