### ISSUE TITLE
Outdated GitHub actions

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/subject-set-search-api#66]
The deployment workflow is still using Node 16. GItHub added a deprecation warning for Node 16 when it reached End-Of-Life in September 2023, and aims to remove support completely by the end of Spring 2024. Dependabot should take care of updating it, though.

```sh
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: 
azure/login@v1, Azure/aks-set-context@v3. 
```
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

EDIT: GitHub will start enforcing the use of Node 20 on 13th May 2024. 
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by eatyourgreens** [comment]
It might alos be worth moving this repo to Node 22, once that comes out next week.

**Comment by zwolf** [comment]
Merged Dependabot PRs.
